<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <PackageIcon>app.ico</PackageIcon>
    <ApplicationIcon>Properties\app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="C:\Users\Kyousukee\.nuget\packages\nlog.config\4.7.15\contentFiles\any\any\NLog.config" />
    <None Remove="NLog.config" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Properties\app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.PDF" Version="25.4.0" />
    <PackageReference Include="BCrypt.Net" Version="0.1.0" />
    <PackageReference Include="ClosedXML" Version="0.104.2" />
    <PackageReference Include="FontAwesome.Sharp" Version="6.6.0" />
    <PackageReference Include="itext" Version="9.1.0" />
    <PackageReference Include="itext.pdfhtml" Version="6.1.0" />
    <PackageReference Include="itext7" Version="9.1.0" />
    <PackageReference Include="itext7.bouncy-castle-adapter" Version="9.1.0" />
    <PackageReference Include="itext7.pdfhtml" Version="6.1.0" />
    <PackageReference Include="iTextSharp" Version="5.5.13.4" />
    <PackageReference Include="LiveCharts.WinForms" Version="0.9.7.1" />
    <PackageReference Include="MaterialSkin.2" Version="2.3.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.2" />
    <PackageReference Include="MySql.Data" Version="9.3.0" />
    <PackageReference Include="NLog" Version="5.4.0" />
    <PackageReference Include="NLog.Config" Version="4.7.15" />
    <PackageReference Include="NLog.Database" Version="5.4.0" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.4.0" />
    <PackageReference Include="NLog.Schema" Version="5.4.0" />
    <PackageReference Include="PdfPig" Version="0.1.10" />
    <PackageReference Include="PetaPoco" Version="5.1.304" />
    <PackageReference Include="PetaPoco.Compiled" Version="6.0.683" />
    <PackageReference Include="Portable.BouncyCastle" Version="1.9.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="log4net.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Properties\app.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="C:\Users\Kyousukee\source\repos\PeopleFlow\PeopleFlow\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\Kyousukee\source\repos\PeopleFlow\PeopleFlow\.editorconfig" />
  </ItemGroup>

</Project>